// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'tree_expert';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String NUNITO_BOLD = 'Nunito-Bold';
  static const String NUNITO_EXTRABOLD = 'Nunito-ExtraBold';
  static const String NUNITO_EXTRALIGHT = 'Nunito-ExtraLight';
  static const String NUNITO_LIGHT = 'Nunito-Light';
  static const String NUNITO_MEDIUM = 'Nunito-Medium';
  static const String NUNITO_REGULAR = 'Nunito-Regular';
  static const String NUNITO_SEMIBOLD = 'Nunito-SemiBold';
  static const String DARK_BLACK_FONT = 'dark_black_font';
}
